token CountRepeat = /[0-9]+\*/ ;
token CollectionOpen = /#\[/ ;
token Number = /[0-9](_?[0-9])*(\.[0-9](_?[0-9])*)?(i32|u32|i64|u64|f32|f64)?/ ;
token Char = /'([^'\\]|\\.)'/ ;
token String = /"([^"\\]|\\.)*"/ ;
token LiteralType = /#([a-z_][a-z0-9_]*|[A-Z][A-Za-z0-9]*)/ ;
token OperatorSymbol = /[+\-*\/%<>=!&|^$]+/ ;
token LowerIdentRepeat = /[a-z_][a-z0-9_]*\*/ ;
token PascalIdentRepeat = /[A-Z][A-Za-z0-9]*\*/ ;
token TypeRepeatPrefix = /([a-z_][a-z0-9_]*|[A-Z][A-Za-z0-9]*|[0-9]+)\*(\s*[0-9]+\*)*/ ;
token LowerIdent = /[a-z_][a-z0-9_]*/ ;
token PascalIdent = /[A-Z][A-Za-z0-9]*/ ;
skip Whitespace = /[ \t\r\n]+/ ;
skip Comment = /\/\/[^\n]*/ ;

Program = Decl* ;
FieldName = LowerIdent ":" ;
Decl = TaggedDecl | TypeAssertDecl | TypeSugarDecl | TypeFnDecl | OperatorDecl | ConstDecl | FnDecl | TopLetDecl ;
TaggedDecl = TagList+ DeclBody ;
DeclBody = TypeAssertDecl | TypeSugarDecl | TypeFnDecl | OperatorDecl | ConstDecl | FnDecl | TopLetDecl ;
TagList = "@[" TagItems "]" ;
TagItems = TagItem ("," TagItem)* ","? ;
TagItem = TypeExpr | Tag ;
Tag = LowerIdent ;
TypeSugarDecl = "type" PascalIdent TypeSugarParams? "=" TypeSugarBody ";"? ;
TypeSugarParams = "(" TypeSugarParamList? ")" ;
TypeSugarParamList = TypeSugarParam ("," TypeSugarParam)* ","? ;
TypeSugarParam = (PascalIdent | LowerIdent) (":" TypeParamKind)? ;
TypeSugarBody = TypeSugarStruct | TypeSugarUnion | TypeSugarEnum | TypeExpr ;
TypeSugarStruct = "struct" TypeShape ;
TypeSugarUnion = "union" "{" TypeSugarVariants? "}" ;
TypeSugarVariants = TypeSugarVariant ("," TypeSugarVariant)* ","? ;
TypeSugarVariant = PascalIdent TypeSugarVariantPayload? ;
TypeSugarVariantPayload = "(" TypeSugarVariantPayloadBody? ")" ;
TypeSugarVariantPayloadBody = TypeShapeSlot ("," TypeShapeSlot)* ","? ;
TypeSugarEnum = "enum" "(" EnumBacking ")" "{" TypeSugarEnumVariants? "}" ;
EnumBacking = ScalarDomainType | ScalarCarrier ;
TypeSugarEnumVariants = TypeSugarEnumVariant ("," TypeSugarEnumVariant)* ","? ;
TypeSugarEnumVariant = PascalIdent "=" (SignedNumber | Number) ;
TypeFnDecl = "type" "fn" PascalIdent "(" TypeParamsDecl? ")" TypeResultSig? TypeBlock ;
TypeBlock = "{" TypeBlockItem* "}" ;
TypeBlockItem = TypeLetDecl | TypeExpr ";"? ;
TypeLetDecl = ("let" | "const") PascalIdent "=" TypeExpr ";" ;
TypeExpr = TypeMembers | TypeMatch | FnType | TypeBinary ;
TypeMembers = "members" "(" TypeExpr ")" TypeMembersBlock ;
TypeMembersBlock = "{" TypeMemberFn* "}" ;
TypeMemberFn = FnTail ;
TypeMatch = "match" TypeExpr "{" TypeArm* "}" ;
TypeArm = TypePattern "=>" TypeExpr ","? ;
TypePattern = "_" | Literal | ScalarCarrier | LowerIdent | PascalIdent ;
TypeBinary = TypeCall (TypeOp TypeCall)* ;
TypeCall = TypePrimary ("(" TypeExprArgs? ")")* ;
TypePrimary = TypeTuple | TypeShape | StaticBuiltin | Literal | TypeHole | TypeBuilderName | ScalarDomainType | ScalarCarrier | LowerIdent TypeQualifiedTail? | PascalIdent TypeQualifiedTail? ;
TypeHole = "_" ;
ScalarDomainType = ScalarCarrier "(" ScalarDomain? ")" ;
ScalarCarrier = "i32" | "i64" | "u32" | "u64" | "f32" | "f64" ;
ScalarDomain = ScalarDomainMember ("|" ScalarDomainMember)* ;
ScalarDomainMember = ScalarDomainEndpoint (".." ScalarDomainEndpoint)? ;
ScalarDomainEndpoint = Literal | LowerIdent TypeQualifiedTail? | PascalIdent TypeQualifiedTail? ;
OperatorDecl = OperatorFixity Number OperatorBindingName "=" OperatorTarget ";"? ;
OperatorFixity = "infixl" | "infixr" | "infix" ;
OperatorBindingName = "(" Op ")" ;
OperatorTarget = (LowerIdent | PascalIdent | ScalarCarrier) TypeQualifiedTail? TypeAssociatedTail? ;
TypeAssociatedTail = "::" (LowerIdent | PascalIdent | ScalarCarrier) ;
TypeQualifiedTail = ("." (LowerIdent | PascalIdent | ScalarCarrier))+ ;
TypeBuilderName = "struct" | "union" ;
StaticBuiltin = "@" (LowerIdent | "import") ;
TypeMember = "const" FieldName Type "=" Expr ;
TypeInlineMember = FnDecl ;
TypeExprArgs = TypeExpr ("," TypeExpr)* ","? ;
FnDecl = Visibility? FnTail ;
FnTail = "fn" FnName "(" Params? ")" ReturnSig? FnBody ;
FnBody = Block | FnMatchBody ;
FnMatchBody = "match" "{" Arm* "}" ;
BranchHint = TagList ;
FnName = (LowerIdent | PascalIdent | ScalarCarrier) ("." (LowerIdent | PascalIdent | ScalarCarrier))* TypeAssociatedTail? ;
FnSig = "fn" FnName "(" Params? ")" ReturnSig? ";" ;
TypeAssertDecl = "@assert" "(" TypeExpr ")" ";"? ;
ConstDecl = "const" (ImportBindingList | FieldName Type | LowerIdent TypeAnn?) "=" (ExternalConstValue | ConstValue) ";"? ;
ImportBindingList = "{" ImportBindingItems ;
ImportBindingItems = "}" | (LowerIdent | PascalIdent) ImportBindingTail ;
ImportBindingTail = "}" | "," "}" | "," ImportBindingItems ;
ExternalConstValue = "@external" "(" String "," FnType ")" ;
ConstValue = Expr ;
TopLetDecl = "let" (TuplePattern "=" Expr ";" | FieldName Type "=" Expr ";" | LowerIdent TopLetTail) ;
TopLetTail = TypeAnn? "=" Expr ";" ;
Block = "{" BlockStmt* Expr? "}" ;
BlockStmt = BlockLetDecl | TypeAssertDecl | DebugTraceStmt ;
BlockLetDecl = "let" (TuplePattern "=" Expr ";" | FieldName Type "=" Expr ";" | LowerIdent BlockLetTail) ;
BlockLetTail = TypeAnn? "=" Expr ";" | ("," LowerIdent)+ "=" Expr ";" ;
DebugTraceStmt = "@trace" "(" Args? ")" ";" ;
Expr = ConstFn | PipeBind ;
DoExpr = "do" DoStrategy DoBlock ;
DoStrategy = StaticBuiltin ("(" TypeExpr ")")? ;
DoBlock = "{" DoBlockBody? "}" ;
DoBlockBody = DoBindStmt DoBlockBody? | DebugTraceStmt DoBlockBody? | DoExprOrFinal | BlockLetDecl DoBlockBody? | TypeAssertDecl DoBlockBody? ;
DoBindStmt = LowerIdent "<-" Expr ";" ;
DoExprOrFinal = Expr (";" DoBlockBody?)? ;
ConstFn = "\\" ConstFnParams "->" (Block | Expr) ;
ConstFnParams = LowerIdent | "(" ConstFnParamList? ")" ;
ConstFnParamList = LowerIdent ("," LowerIdent)* ","? ;
PipeBind = PipeBindAtom ("\\" PipeBindName "->" PipeBindAtom)* ;
PipeBindAtom = IfExpr | MatchExpr | Range ;
IfExpr = "if" IfCondition Block "else" IfElse ;
IfCondition = IfLetCondition | Expr ;
IfLetCondition = "(" "let" Pattern "=" Expr ")" ;
IfElse = IfExpr | Block ;
MatchExpr = "match" MatchValues "{" Arm* "}" ;
MatchValues = MatchValuesParen | Expr ("," Expr)* ","? ;
MatchValuesParen = "(" Expr "," Expr ("," Expr)* ","? ")" ;
Arm = BranchHint? MatchPatterns MatchGuard? "=>" Expr ","? ;
MatchGuard = "if" Expr ;
MatchPatterns = Pattern ("," Pattern)* ","? ;
PipeBindName = LowerIdent ;
Range = Binary (".." Binary)? ;
Binary = Call (Op Call)* ;
Call = Primary ("(" Args? ")" | "." (LowerIdent | PascalIdent | ScalarCarrier) | TypeAssociatedTail | "[" Expr "]")* ;
Primary = DoExpr | ProfileExpr | Literal | StaticBuiltin | TypeBuilderName | ScalarDomainType | ScalarCarrier | LowerIdent | PascalIdent ProductConstructorTail? | ParenExpr | ShapeValue | CollectionValue | TupleValue ;
ProfileExpr = "@profile" "(" Args? ")" Block ;
ProductConstructorTail = ShapeValue ;
ParenExpr = "(" Expr ")" ;
ShapeValue = "{}" | "{" ShapeValueItems ;
ShapeValueItems = SpreadSlot ShapeValueTail | ShapeValueSlotKey Expr ShapeValueTail | PunnedShapeValueSlot ShapeValueTail ;
ShapeValueTail = "}" | "," "}" | "," ShapeValueItems ;
ShapeValueSlot = ShapeValueSlotKey Expr ;
PunnedShapeValueSlot = LowerIdent ;
ShapeValueSlotKey = LowerIdent SlotPosition? ":" | SlotPosition ":" ;
SpreadSlot = "..." Expr ;
SlotPosition = "[" Number "]" ;
CollectionValue = CollectionOpen CollectionValueItems ;
CollectionValueItems = "]" | CollectionSpreadSlot CollectionValueTail | CollectionOverrideSlot CollectionValueTail | CollectionExpr CollectionValueTail ;
CollectionValueTail = "]" | "," CollectionValueItems ;
CollectionSpreadSlot = "..." CollectionExpr ;
CollectionOverrideSlot = "[" Expr "]" ":" CollectionExpr ;
CollectionExpr = CollectionPipeBind ;
CollectionPipeBind = CollectionPipeBindAtom ("\\" PipeBindName "->" CollectionPipeBindAtom)* ;
CollectionPipeBindAtom = IfExpr | MatchExpr | Range ;
TupleValue = "[" TupleValueItems ;
TupleValueItems = "]" | TupleSpreadSlot TupleValueTail | TupleOverrideSlot TupleValueTail | TupleValueRepeat | Expr TupleValueTail ;
TupleValueTail = "]" | "," TupleValueItems ;
TupleSpreadSlot = "..." Expr ;
TupleOverrideSlot = "[" Expr "]" ":" Expr ;
TupleValueRepeat = Expr ";" TypeRepeatCount "]" ;
Pattern = PatternOr PatternTypeAnn? ;
PatternTypeAnn = ":" Type ;
PatternOr = PatternAs ("|" PatternAs)* ;
PatternAs = LowerIdent "@" PatternAs | PatternBase ;
PatternBase = "_" | TuplePattern | PatternGroup | ProductPattern | PatternMember | PatternIdent | Literal ;
PatternGroup = "(" Pattern ")" ;
ProductPattern = ProductPatternName "{" ProductPatternFields? "}" ;
ProductPatternName = (LowerIdent | PascalIdent) TypeQualifiedTail? ;
ProductPatternFields = ProductPatternField ("," ProductPatternField)* ","? ;
ProductPatternField = LowerIdent ":" Pattern | LowerIdent ;
PatternMember = (LowerIdent | PascalIdent) (TypeQualifiedTail TypeAssociatedTail? | TypeAssociatedTail) ;
PatternIdent = LowerIdent | PascalIdent ("(" PatternArgs? ")")? ;
PatternArgs = Pattern ("," Pattern)* ","? ;
TuplePattern = "[" TuplePatternItems ;
TuplePatternItems = "]" | Pattern TuplePatternTail ;
TuplePatternTail = "]" | "," TuplePatternItems ;
Params = Param ("," Param)* ","? ;
Param = ConstTypeFnParam | "const"? (FieldName Type? | Literal TypeAnn? | "_" TypeAnn? | TuplePattern ParamTail? | PatternIdent ParamTail? | ScalarCarrier ParamTail?) ;
ConstTypeFnParam = "const" (LowerIdent | PascalIdent) ":" "type" "fn" TypeConstructorTail ;
ParamTail = ":" Type? | Type ;
Args = Expr ("," Expr)* ","? ;
Type = FnType | TypeUnion ;
TypeUnion = TypeAtom ("|" TypeAtom)* ;
TypeAtom = "type" | "const" | Literal | TypeHole | TypeBuilderName TypeArgs? | ScalarDomainType | ScalarCarrier | LowerIdent TypeQualifiedTail? TypeArgs? | PascalIdent TypeQualifiedTail? TypeArgs? | ShapeType | TupleType ;
FnType = "fn" "(" Params? ")" ReturnSig ;
TypeArgs = "(" TypeExpr ("," TypeExpr)* ")" ;
TypeParamsDecl = TypeParamDecl ("," TypeParamDecl)* ","? ;
TypeParamDecl = (PascalIdent ":" | FieldName | LowerIdent ":" | ScalarCarrier ":" | Literal ":" | "_" ":") TypeParamKind ;
TypeParamKind = "type" TypeKindTail? | "const" | LowerIdent ;
TypeKindTail = "fn" TypeConstructorTail ;
TypeConstructorTail = "(" TypeParamsDecl? ")" TypeResultSig ;
TypeResultSig = "->" TypeResultKind ;
TypeResultKind = "type" | "struct" | "union" | "members" ;
TypeAnn = ":" Type ;
ReturnSig = "->" Type ;
ShapeType = "{}" | "{" ShapeTypeBody ;
ShapeTypeBody = ShapeSlot ShapeTypeTail ;
ShapeTypeTail = "}" | "," "}" | "," ShapeTypeBody ;
ShapeSlot = ShapeSlotKey? ShapeSlotBody ;
ShapeSlotKey = LowerIdent SlotPosition? ":" | SlotPosition ":" ;
ShapeSlotBody = CountRepeat Type | LowerIdentRepeat Type | PascalIdentRepeat Type | LowerIdent TypeArgs? | PascalIdent TypeArgs? | ShapeType ;
TupleType = "[" TupleTypeBody ;
TupleTypeBody = "]" | TupleTypeRepeat | Type TupleTypeTail ;
TupleTypeTail = "," "]" | "," Type TupleTypeMore ;
TupleTypeMore = "]" | "," "]" | "," Type TupleTypeMore ;
TupleTypeRepeat = Type ";" TypeRepeatCount "]" ;
TypeShape = "{}" | "{" TypeShapeBody ;
TypeShapeBody = TypeShapeSlot TypeShapeTail ;
TypeShapeTail = "}" | "," "}" | "," TypeShapeBody ;
TypeShapeSlot = ShapeSlotKey? TypeShapeSlotBody ;
TypeShapeSlotBody = TypeShapeRepeat TypeExpr | TypeExpr ;
TypeShapeAnonSlotBody = TypeShapeRepeat TypeNonFnExpr | TypeNonFnExpr ;
TypeTuple = "[" TypeTupleBody ;
TypeTupleBody = "]" | TypeTupleRepeat | TypeExpr TypeTupleTail ;
TypeTupleTail = "," "]" | "," TypeExpr TypeTupleMore ;
TypeTupleMore = "]" | "," "]" | "," TypeExpr TypeTupleMore ;
TypeTupleRepeat = TypeExpr ";" TypeRepeatCount "]" ;
TypeNonFnExpr = TypeMatch | TypeBinary ;
TypeShapeRepeat = CountRepeat | LowerIdentRepeat | PascalIdentRepeat | TypeRepeatPrefix ;
TypeRepeatCount = Number | LowerIdent | PascalIdent ;
Visibility = "pub" ;
Literal = SignedNumber | Number | Bool | Char | String | fenced_text | LiteralType ;
SignedNumber = "-" Number ;
Bool = "true" | "false" ;
Op = OperatorSymbol ;
TypeOp = Op ;
