[[language]]
name = "fig"
scope = "source.fig"
file-types = ["fig"]
grammar = "fig"
roots = ["deno.json", "grammar.ebnf"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "fig"
source = { path = "generated/baba-workbench" }
