[[language]]
name = "shovel"
scope = "source.shovel"
file-types = ["shovel"]
grammar = "shovel"
roots = ["deno.json", "grammar.ebnf"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "shovel"
source = { path = "generated/baba-workbench" }
