type BabaModule = {
  parseGrammar(source: string): unknown;
  parseMetadata(source: string): unknown;
};

type BabaAdvancedModule = {
  createLexicalSpec(grammar: unknown, options: { skipValidation: boolean }): unknown;
  generateLexicalManifest(grammar: unknown, options: { spec: unknown }): string;
  generateTokenizerSource(
    grammar: unknown,
    options: { spec: unknown; metadata: unknown; skipValidation: boolean },
  ): string;
  generateTreeSitterGrammar(
    grammar: unknown,
    options: { name: string; metadata: unknown; skipValidation: boolean },
  ): string;
  generateWorkbenchQueries(
    grammar: unknown,
    options: { metadata: unknown; skipValidation: boolean },
  ): Record<string, string>;
};

const dynamicImport = new Function("specifier", "return import(specifier)") as <T>(
  specifier: string,
) => Promise<T>;
const { parseGrammar, parseMetadata } = await dynamicImport<BabaModule>("@mewhhaha/baba");
const {
  createLexicalSpec,
  generateLexicalManifest,
  generateTokenizerSource,
  generateTreeSitterGrammar,
  generateWorkbenchQueries,
} = await dynamicImport<BabaAdvancedModule>("@mewhhaha/baba/advanced");

const grammarSource = await Deno.readTextFile("grammar.ebnf");
const metadataSource = await Deno.readTextFile("baba.json");
const grammar = parseGrammar(grammarSource);
const metadata = parseMetadata(metadataSource);
const spec = createLexicalSpec(grammar, { skipValidation: true });
const queries = generateWorkbenchQueries(grammar, {
  metadata,
  skipValidation: true,
});
const files: Array<{ path: string; content: string }> = [
  { path: "lexical.json", content: generateLexicalManifest(grammar, { spec }) },
  {
    path: "tokenizer.ts",
    content: generateTokenizerSource(grammar, {
      spec,
      metadata,
      skipValidation: true,
    }),
  },
  {
    path: "grammar.js",
    content: generateTreeSitterGrammar(grammar, {
      name: "fig",
      metadata,
      skipValidation: true,
    }),
  },
  ...Object.entries(queries).map(([path, content]) => ({ path: `queries/${path}`, content })),
];

const bundle = { files };

/*
 * Fig's grammar intentionally has tree-sitter conflicts such as do-bind vs expression statements.
 * Baba's generated parser is predictive and rejects those shapes, so the compiler parser sources
 * stay checked in until Baba exposes a non-predictive parser generator path.
 */
await Deno.mkdir("generated/baba-workbench", { recursive: true });

for (const file of bundle.files) {
  const path = `generated/baba-workbench/${file.path}`;
  const slash = path.lastIndexOf("/");
  if (slash >= 0) await Deno.mkdir(path.slice(0, slash), { recursive: true });
  let content = file.content;
  if (file.path === "grammar.js") {
    content = content.replace("Comment: $ => /\\\\/\\\\/[^\\n]*/", "Comment: $ => /\\/\\/[^\\n]*/");
  }
  if (file.path === "queries/highlights.scm") {
    content = content
      .replace("(TypeAtom (LowerIdent) @type)", "(TypeAtom (LowerIdent) @type.parameter)")
      .replace('"." @punctuation.delimiter\n', '"." @punctuation.delimiter\n".." @operator\n')
      .replace("(TypeAtom (PascalIdent) @type.parameter)\n", "")
      .replace("(TypePrimary (LowerIdent) @type)\n", "")
      .replace("(TypePrimary (PascalIdent) @type.parameter)\n", "")
      .replace("(TypeFnDecl (LowerIdent) @type.definition)\n", "")
      .replace("(TypeFnDecl (PascalIdent) @type.definition)", "(TypeFnDecl (PascalIdent) @type)")
      .replace("(TypeLetDecl (PascalIdent) @type)\n", "")
      .replace("(BlockProofConstDecl (PascalIdent) @type)\n", "")
      .replace(
        "(ImportBindingItems (PascalIdent) @type.definition)",
        "(ImportBindingItems (PascalIdent) @type)",
      )
      .replace("(CollectionOpen) @constant\n", "")
      .replace("(DoBindName) @constant\n", "");
    content += [
      "(DoStrategy (StaticBuiltin) @keyword.directive)",
      "(BranchHint) @keyword.directive",
      "(DoBindStmt (LowerIdent) @variable)",
      "(CollectionValue (CollectionOpen) @punctuation.bracket)",
      "(Op) @operator",
    ].join("\n") + "\n";
  }
  await Deno.writeTextFile(path, content);
}

await Deno.remove("helix/runtime/queries/fig", { recursive: true }).catch(() => {});
await Deno.mkdir("helix/runtime/queries/fig", { recursive: true });
for await (const entry of Deno.readDir("generated/baba-workbench/queries")) {
  if (!entry.isFile || !entry.name.endsWith(".scm")) continue;
  await Deno.copyFile(
    `generated/baba-workbench/queries/${entry.name}`,
    `helix/runtime/queries/fig/${entry.name}`,
  );
}

const tokenKinds = [
  "import",
  "external",
  "type",
  "contract",
  "const",
  "fn",
  "rewrite",
  "if",
  "else",
  "let",
  "match",
  "pub",
  "bool",
  "zip",
  "identifier",
  "number",
  "string",
  "char",
  "multiline",
  "literalType",
  "symbol",
];

await Deno.writeTextFile(
  "generated/tokenizer.ts",
  `// Generated by scripts/generate_grammar.ts from grammar.ebnf via @mewhhaha/baba.\n` +
    `export const tokenKinds = ${JSON.stringify(tokenKinds, null, 2)} as const;\n` +
    `export type GeneratedTokenKind = typeof tokenKinds[number];\n`,
);
