import { generate, parseGrammar, parseMetadata } from "@mewhhaha/baba";

const grammarSource = await Deno.readTextFile("grammar.ebnf");
const metadataSource = await Deno.readTextFile("baba.json");
const grammar = parseGrammar(grammarSource);
const metadata = parseMetadata(metadataSource);
const bundle = generate(grammar, { name: "fig", metadata, preset: "workbench" });

await Deno.remove("generated/baba-workbench", { recursive: true }).catch(() => {});
await Deno.mkdir("generated/baba-workbench", { recursive: true });
for (const file of bundle.files) {
  const path = `generated/baba-workbench/${file.path}`;
  const slash = path.lastIndexOf("/");
  if (slash >= 0) await Deno.mkdir(path.slice(0, slash), { recursive: true });
  let content = file.content;
  if (file.path === "grammar.js") {
    content = content.replace("Comment: $ => /\\\\/\\\\/[^\\n]*/", "Comment: $ => /\\/\\/[^\\n]*/");
  }
  if (file.path === "queries/highlights.scm") {
    content = content
      .replace("(TypeAtom (LowerIdent) @type)", "(TypeAtom (LowerIdent) @type.parameter)")
      .replace('"." @punctuation.delimiter\n', '"." @punctuation.delimiter\n".." @operator\n')
      .replace("(TypeAtom (PascalIdent) @type.parameter)\n", "")
      .replace("(TypePrimary (LowerIdent) @type)\n", "")
      .replace("(TypePrimary (PascalIdent) @type.parameter)\n", "")
      .replace("(TypeFnDecl (LowerIdent) @type.definition)\n", "")
      .replace("(TypeLetDecl (PascalIdent) @type)\n", "")
      .replace("(BlockProofConstDecl (PascalIdent) @type)\n", "");
  }
  await Deno.writeTextFile(path, content);
}

await Deno.remove("helix/runtime/queries/fig", { recursive: true }).catch(() => {});
await Deno.mkdir("helix/runtime/queries/fig", { recursive: true });
for await (const entry of Deno.readDir("generated/baba-workbench/queries")) {
  if (!entry.isFile || !entry.name.endsWith(".scm")) continue;
  await Deno.copyFile(
    `generated/baba-workbench/queries/${entry.name}`,
    `helix/runtime/queries/fig/${entry.name}`,
  );
}

const tokenKinds = [
  "import",
  "capability",
  "type",
  "const",
  "fn",
  "if",
  "else",
  "let",
  "match",
  "pub",
  "bool",
  "zip",
  "identifier",
  "number",
  "string",
  "char",
  "multiline",
  "literalType",
  "symbol",
];

await Deno.writeTextFile(
  "generated/tokenizer.ts",
  `// Generated by scripts/generate_grammar.ts from grammar.ebnf via @mewhhaha/baba.\n` +
    `export const tokenKinds = ${JSON.stringify(tokenKinds, null, 2)} as const;\n` +
    `export type GeneratedTokenKind = typeof tokenKinds[number];\n`,
);
